# Generated by Django 4.1 on 2022-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='favicon',
            field=models.URLField(default='{{ models.link }}favicon.ico', max_length=500),
        ),
    ]
