# Generated by Django 4.1 on 2022-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_link_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='favicon',
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
