# Generated by Django 4.1 on 2022-11-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_link_favicon_alter_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
